---
title: "ITU REG4COVID Data Analysis"
author: "Carina Peng"
date: "6/12/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl)
library(magrittr)
library(dplyr)
library(janitor)
library(tidyr)
library(ggplot2)
library(ggthemes)
library(tidyverse)
library(waffle)
library(ggrepel)
library(RColorBrewer)

nb.cols <- 17
mycolors <- colorRampPalette(brewer.pal(17, "Blues"))(nb.cols)
```

```{r, include = FALSE}
data <- read_excel("/Users/carinapeng/Downloads/reg4covid.xlsx") %>%
  clean_names()

mutated <- data %>%
  mutate(emergency = ifelse(is.na(topic_s), 0, 1),
         broadband = ifelse(is.na(x11), 0, 1),
         affordability = ifelse(is.na(x12), 0, 1),
         accessibility = ifelse(is.na(x13), 0, 1),
         quality_service = ifelse(is.na(x14), 0, 1),
         traffic = ifelse(is.na(x15), 0, 1),
         consumer = ifelse(is.na(x16), 0, 1),
         universal = ifelse(is.na(x17), 0, 1),
         privacy = ifelse(is.na(x18), 0, 1),
         digital_id = ifelse(is.na(x19), 0, 1),
         reg_innov = ifelse(is.na(x20), 0, 1),
         reg_harmon = ifelse(is.na(x21), 0, 1),
         spectrum = ifelse(is.na(x22), 0, 1),
         financial = ifelse(is.na(x23), 0, 1),
         other = ifelse(is.na(x24), 0, 1),
         broadcasting = ifelse(is.na(x25), 0, 1))

new_data <- mutated %>%
  select(country_economy, 
         level_of_development, 
         region, 
         emergency,
         broadband,
         affordability,
         accessibility,
         quality_service,
         traffic,
         consumer,
         universal,
         privacy,
         digital_id,
         reg_innov,
         reg_harmon,
         spectrum,
         financial,
         other,
         broadcasting)


emergency_count <- new_data %>%
  filter(emergency == 1) %>%
  count(region) %>%
  rename(emergency_c = n)

broadband_count <- new_data %>%
  filter(broadband == 1) %>%
  count(region) %>%
  rename(broadband_c = n)

affordability_count <- new_data %>%
  filter(affordability == 1) %>%
  count(region) %>%
  rename(affordability_c = n)

accessibility_count <- new_data %>%
  filter(accessibility == 1) %>%
  count(region) %>%
  rename(accessibility_c = n)

quality_service_count <- new_data %>%
  filter(quality_service == 1) %>%
  count(region) %>%
  rename(quality_service_c = n)

traffic_count <- new_data %>%
  filter(traffic == 1) %>%
  count(region) %>%
  rename(traffic_c = n)

consumer_count <- new_data %>%
  filter(consumer == 1) %>%
  count(region) %>%
  rename(consumer_c = n)

universal_count <- new_data %>%
  filter(universal == 1) %>%
  count(region) %>%
  rename(universal_c = n)

privacy_count <- new_data %>%
  filter(privacy == 1) %>%
  count(region) %>%
  rename(privacy_c = n)

digital_id_count <- new_data %>%
  filter(digital_id == 1) %>%
  count(region) %>%
  rename(digital_id_c = n)

reg_innov_count <- new_data %>%
  filter(reg_innov == 1) %>%
  count(region) %>%
  rename(reg_innov_c = n)

reg_harmon_count <- new_data %>%
  filter(reg_harmon == 1) %>%
  count(region) %>%
  rename(reg_harmon_c = n)

spectrum_count <- new_data %>%
  filter(spectrum == 1) %>%
  count(region) %>%
  rename(spectrum_c = n)

financial_count <- new_data %>%
  filter(financial == 1) %>%
  count(region) %>%
  rename(financial_c = n)

other_count <- new_data %>%
  filter(other == 1) %>%
  count(region) %>%
  rename(other_c = n)

broadcasting_count <- new_data %>%
  filter(broadcasting == 1) %>%
  count(region) %>%
  rename(broadcasting_c = n)
  
```


```{r, include = FALSE}

region_tidy <- emergency_count %>%
  left_join(broadband_count) %>%
  left_join(affordability_count) %>%
  left_join(accessibility_count) %>%
  left_join(quality_service_count) %>%
  left_join(traffic_count) %>%
  left_join(consumer_count) %>%
  left_join(universal_count) %>%
  left_join(privacy_count) %>%
  left_join(digital_id_count) %>%
  left_join(reg_innov_count) %>%
  left_join(reg_harmon_count) %>%
  left_join(spectrum_count) %>%
  left_join(financial_count) %>%
  left_join(other_count) %>%
  left_join(broadcasting_count)

region_tidy <- region_tidy %>%
  mutate_all(~replace(., is.na(.), 0))

```

```{r, echo = FALSE}
  
bar_topfive <- region_tidy %>%
  select(region,
         emergency_c,
         affordability_c,
         accessibility_c,
         broadband_c,
         other_c) %>%
  pivot_longer(names_to = "type",
               values_to = "number",
               cols = -region) 

# Set 0 values to NA, and then omit these values
bar_topfive[bar_topfive == 0] <- NA

bar_topfive <- bar_topfive %>%
  na.omit(region)
  
bar_region <- bar_topfive %>%
  ggplot(aes(fill=region, y=number, x=type)) +
  geom_bar(position="dodge", stat="identity") +
  geom_text(aes(label=number), position = position_dodge(width = 1), vjust=-0.3, size=3) +
  theme(axis.text.x = element_text(angle = 60, hjust = 1)) +
  labs(
    title = "COVID-19 Initiatives and Policy Measures",
    subtitle = "Grouped by Regions",
    caption = "Data from ITU REG4COVID team",
    x = "Type of Policy Measures",
    y = "Number",
    fill = "Region"
  ) +
  scale_fill_brewer(palette="Blues") +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  scale_x_discrete(breaks=c("accessibility_c","affordability_c","broadband_c", "emergency_c", "other_c"),
        labels=c("Accessibility", "Affordability", "Broadband", "Emergency", "Other"))

bar_region

```

```{r, echo = FALSE}
dev <- read_excel("/Users/carinapeng/REG4COVID/dev.xlsx") %>%
  clean_names() %>%
  select(level_of_development,
         emergency_telecommunications,
         affordability,
         accessibility,
         broadband_availability,
         other) %>%
  pivot_longer(names_to = "type",
               values_to = "number",
               cols = -level_of_development)

bar_dev <- dev %>%
  ggplot(aes(fill=level_of_development, y=number, x=type)) +
  geom_bar(position="dodge", stat="identity") + 
  geom_text(aes(label=number), position = position_dodge(width = 1), vjust=-0.3, size=3) +
  theme(axis.text.x = element_text(angle = 60, hjust = 1)) +
  labs(
    title = "COVID-19 Initiatives and Policy Measures",
    subtitle = "Grouped by Countries' Level of Development",
    caption = "Data from ITU REG4COVID team",
    x = "Type of Policy Measures",
    y = "Number",
    fill = "Level of Development"
  ) +
  scale_fill_brewer(palette="Blues") +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  scale_x_discrete(breaks=c("accessibility","affordability","broadband_availability", "emergency_telecommunications", "other"),
        labels=c("Accessibility", "Affordability", "Broadband", "Emergency", "Other"))

bar_dev
```



```{r, echo = FALSE}

pie_region_data <- region_tidy %>%
  pivot_longer(names_to = "type",
               values_to = "number",
               cols = -region)

pie_region_data$type <- factor(pie_region_data$type, 
                        levels=c("emergency_c",
                                 "broadband_c",
                                 "affordability_c",
                                 "accessibility_c",
                                 "quality_service_c",
                                 "traffic_c",
                                 "consumer_c",
                                 "universal_c",
                                 "privacy_c",
                                 "digital_id_c",
                                 "reg_innov_c",
                                 "reg_harmon_c",
                                 "spectrum_c",
                                 "financial_c",
                                 "other_c",
                                 "broadcasting_c"), 
                        labels=c("Emergency",
                                 "Broadband",
                                 "Affordability",
                                 "Accessibility",
                                 "Quality Service",
                                 "Traffic",
                                 "Consumer",
                                 "Universal",
                                 "Privacy",
                                 "Digital ID",
                                 "Regulatory Innovation",
                                 "Regulatory Harmonization",
                                 "Spectrum",
                                 "Financial",
                                 "Other",
                                 "Broadcasting"))

africa_pie <- pie_region_data %>%
  filter(region == "Africa") %>%
  ggplot(aes(x="", y=number, fill=type)) +
  geom_bar(width = 1, stat = "identity") +
  coord_polar("y", start = 0) +
  scale_fill_manual(values = rev(mycolors)) +
  theme_void() +
  labs(title = "COVID-19 Initiatives and Policy Measures in Africa",
       subtitle = "Grouped by Topics",
       caption = "Data collection from the ITU REG4COVID team",
       fill = "Type of Measures")

arab_states_pie <- pie_region_data %>%
  filter(region == "Arab States") %>%
  ggplot(aes(x="", y=number, fill=type)) +
  geom_bar(width = 1, stat = "identity") +
  coord_polar("y", start = 0) +
  scale_fill_manual(values = rev(mycolors)) +
  theme_void() +
  labs(title = "COVID-19 Initiatives and Policy Measures in Arab States",
       subtitle = "Grouped by Topics",
       caption = "Data collection from the ITU REG4COVID team",
       fill = "Type of Measures")

asia_pie <- pie_region_data %>%
  filter(region == "Asia & Pacific") %>%
  ggplot(aes(x="", y=number, fill=type)) +
  geom_bar(width = 1, stat = "identity") +
  coord_polar("y", start = 0) +
  scale_fill_manual(values = rev(mycolors)) +
  theme_void() +
  labs(title = "COVID-19 Initiatives and Policy Measures in Asia and the Pacific",
       subtitle = "Grouped by Topics",
       caption = "Data collection from the ITU REG4COVID team",
       fill = "Type of Measures")

cis_pie <- pie_region_data %>%
  filter(region == "CIS countries") %>%
  ggplot(aes(x="", y=number, fill=type)) +
  geom_bar(width = 1, stat = "identity") +
  coord_polar("y", start = 0) +
  scale_fill_manual(values = rev(mycolors)) +
  theme_void() +
  labs(title = "COVID-19 Initiatives and Policy Measures in CIS Countries",
       subtitle = "Grouped by Topics",
       caption = "Data collection from the ITU REG4COVID team",
       fill = "Type of Measures")

europe_pie <- pie_region_data %>%
  filter(region == "Europe") %>%
  ggplot(aes(x="", y=number, fill=type)) +
  geom_bar(width = 1, stat = "identity") +
  coord_polar("y", start = 0) +
  scale_fill_manual(values = rev(mycolors)) +
  theme_void() +
  labs(title = "COVID-19 Initiatives and Policy Measures in Europe",
       subtitle = "Grouped by Topics",
       caption = "Data collection from the ITU REG4COVID team",
       fill = "Type of Measures")

# americas <- americas %>%
  # mutate(pct = paste(round((number / sum(number))*100, digits = 2), "%", sep = ""))


americas_pie <- pie_region_data %>%
  filter(region == "The Americas") %>%
  ggplot(aes(x="", y=number, fill=type)) +
  geom_bar(width = 1, stat = "identity") +
  coord_polar("y", start = 0) +
  scale_fill_manual(values = rev(mycolors)) +
  theme_void() +
  labs(title = "COVID-19 Initiatives and Policy Measures in The Americas",
       subtitle = "Grouped by Topics",
       caption = "Data collection from the ITU REG4COVID team",
       fill = "Type of Measures")
africa_pie
arab_states_pie
asia_pie
cis_pie
europe_pie
americas_pie

```
               





